// Portfolios
export const REQUEST_PORTFOLIOS_LIST = 'REQUEST_PORTFOLIOS_LIST';
export const REQUEST_PORTFOLIOS_LIST_FULFILLED = 'REQUEST_PORTFOLIOS_LIST_FULFILLED';

export const REQUEST_PORTFOLIO_DETAILS = 'REQUEST_PORTFOLIO_DETAILS';
export const REQUEST_PORTFOLIO_DETAILS_FULFILLED  = 'REQUEST_PORTFOLIO_DETAILS_FULFILLED';

export const REQUEST_PORTFOLIO_FINANCIALS = 'REQUEST_PORTFOLIO_FINANCIALS';
export const REQUEST_PORTFOLIO_FINANCIALS_FULFILLED  = 'REQUEST_PORTFOLIO_FINANCIALS_FULFILLED';

export const REQUEST_PORTFOLIO_STOCKS_LIST = 'REQUEST_PORTFOLIO_STOCKS_LIST';
export const REQUEST_PORTFOLIO_STOCKS_LIST_FULFILLED  = 'REQUEST_PORTFOLIO_STOCKS_LIST_FULFILLED';

// Stocks
export const REQUEST_STOCKS_LIST = 'REQUEST_STOCKS_LIST';
export const REQUEST_STOCKS_LIST_FULFILLED = 'REQUEST_STOCKS_LIST_FULFILLED';

export const REQUEST_STOCK_QUOTE = 'REQUEST_STOCK_QUOTE';
export const REQUEST_STOCK_QUOTE_FULFILLED = 'REQUEST_STOCK_QUOTE_FULFILLED';

export const SELL_PORTFOLIO_STOCK = 'SELL_PORTFOLIO_STOCK';
export const SELL_PORTFOLIO_STOCK_FULFILLED = 'SELL_PORTFOLIO_STOCK_FULFILLED';